# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    groups:
      prod-deps-security:
        applies-to: "security-updates"
        dependency-type: "production"
      dev-deps-security:
        applies-to: "security-updates"
        dependency-type: "development"
      prod-deps:
        applies-to: "version-updates"
        dependency-type: "production"
      dev-deps:
        applies-to: "version-updates"
        dependency-type: "development"
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
      - dependency-name: "typescript"
        update-types:
          - "version-update:semver-major"
          - "version-update:semver-minor"
          - "version-update:semver-patch"
