#!/bin/sh

# SPDX-FileCopyrightText: 2024 KindSpells Labs S.L.
#
# SPDX-License-Identifier: MIT

set -eu
set -o pipefail

check_astro_shield () {
	cd "@kindspells/astro-shield";
	pnpm lint;
	pnpm test:unit;
	cd -;
}

check_astro_shield;
